-- MySQL Script generated by MySQL Workbench
-- Sun Feb 25 20:27:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbtodo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbtodo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbtodo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dbtodo` ;

-- -----------------------------------------------------
-- Table `dbtodo`.`tblpriorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtodo`.`tblpriorities` ;

CREATE TABLE IF NOT EXISTS `dbtodo`.`tblpriorities` (
  `prtIdpk` INT NOT NULL AUTO_INCREMENT,
  `prtName` VARCHAR(20) NOT NULL,
  `prtDescription` VARCHAR(255) NOT NULL,
  `prtCreatedDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `prtLastEditDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `prtIsActive` BIT(1) NULL DEFAULT b'1',
  PRIMARY KEY (`prtIdpk`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbtodo`.`tblprojects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtodo`.`tblprojects` ;

CREATE TABLE IF NOT EXISTS `dbtodo`.`tblprojects` (
  `prjIdpk` INT NOT NULL AUTO_INCREMENT,
  `prjName` VARCHAR(50) NOT NULL,
  `prjDescription` VARCHAR(255) NOT NULL,
  `prjIsActive` BIT(1) NOT NULL DEFAULT b'1',
  `prjStartDate` DATETIME NULL DEFAULT NULL,
  `prjEndDate` DATETIME NULL DEFAULT NULL,
  `prjCreatedDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `prjLastEditDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `prjType` VARCHAR(100) NULL DEFAULT NULL,
  `prjStaIdfk` INT NULL DEFAULT NULL,
  `prjPrtIdfk` INT NULL DEFAULT NULL,
  PRIMARY KEY (`prjIdpk`),
  INDEX `prjStaIdfk` (`prjStaIdfk` ASC) VISIBLE,
  INDEX `prjPrtIdfk` (`prjPrtIdfk` ASC) VISIBLE,
  CONSTRAINT `tblprojects_ibfk_1`
    FOREIGN KEY (`prjStaIdfk`)
    REFERENCES `dbtodo`.`tbltaskstatuses` (`staIdpk`),
  CONSTRAINT `tblprojects_ibfk_2`
    FOREIGN KEY (`prjPrtIdfk`)
    REFERENCES `dbtodo`.`tblpriorities` (`prtIdpk`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbtodo`.`tbltaskassignments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtodo`.`tbltaskassignments` ;

CREATE TABLE IF NOT EXISTS `dbtodo`.`tbltaskassignments` (
  `tkaIdpk` INT NOT NULL AUTO_INCREMENT,
  `tkaAssignerUsrIdfk` INT NULL DEFAULT NULL,
  `tkaRemarks` VARCHAR(255) NULL DEFAULT NULL,
  `tkaCreatedDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tkaUpdatedDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tkaIsActive` BIT(1) NOT NULL DEFAULT b'1',
  `tkaAssigneeUsrIdfk` INT NOT NULL,
  `tkaTskIdfk` INT NOT NULL,
  `tkaStaIdfk` INT NOT NULL,
  `tkaPrtIdfk` INT NOT NULL,
  `tkaProgress` DECIMAL(6,3) NULL DEFAULT '0.000',
  PRIMARY KEY (`tkaIdpk`),
  INDEX `tkaAssigneeUsrIdfk` (`tkaAssigneeUsrIdfk` ASC) VISIBLE,
  INDEX `tkaAssignerUsrIdfk` (`tkaAssignerUsrIdfk` ASC) VISIBLE,
  INDEX `tkaTskIdfk` (`tkaTskIdfk` ASC) VISIBLE,
  INDEX `tkaPrtIdfk` (`tkaPrtIdfk` ASC) VISIBLE,
  CONSTRAINT `tbltaskassignments_ibfk_1`
    FOREIGN KEY (`tkaAssigneeUsrIdfk`)
    REFERENCES `dbtodo`.`tblusers` (`usrIdpk`),
  CONSTRAINT `tbltaskassignments_ibfk_2`
    FOREIGN KEY (`tkaAssignerUsrIdfk`)
    REFERENCES `dbtodo`.`tblusers` (`usrIdpk`),
  CONSTRAINT `tbltaskassignments_ibfk_3`
    FOREIGN KEY (`tkaTskIdfk`)
    REFERENCES `dbtodo`.`tbltasks` (`tskIdpk`),
  CONSTRAINT `tbltaskassignments_ibfk_4`
    FOREIGN KEY (`tkaPrtIdfk`)
    REFERENCES `dbtodo`.`tblpriorities` (`prtIdpk`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbtodo`.`tbltasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtodo`.`tbltasks` ;

CREATE TABLE IF NOT EXISTS `dbtodo`.`tbltasks` (
  `tskIdpk` INT NOT NULL AUTO_INCREMENT,
  `tskSlug` CHAR(32) NOT NULL,
  `tskName` VARCHAR(150) NOT NULL,
  `tskDescription` VARCHAR(255) NOT NULL,
  `tkaCreatedDate` DATETIME NOT NULL,
  `tkaLastEditDate` DATETIME NOT NULL,
  `tskStartDate` DATE NULL DEFAULT NULL,
  `tskEndDate` DATE NULL DEFAULT NULL,
  `tskIsActive` BIT(1) NULL DEFAULT b'1',
  `tskStaIdfk` INT NOT NULL,
  `tskPriorityIdfk` INT NOT NULL,
  PRIMARY KEY (`tskIdpk`),
  UNIQUE INDEX `tskSlug` (`tskSlug` ASC) VISIBLE,
  INDEX `tskStaIdfk` (`tskStaIdfk` ASC) VISIBLE,
  CONSTRAINT `tbltasks_ibfk_1`
    FOREIGN KEY (`tskStaIdfk`)
    REFERENCES `dbtodo`.`tbltaskstatuses` (`staIdpk`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbtodo`.`tbltaskstatuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtodo`.`tbltaskstatuses` ;

CREATE TABLE IF NOT EXISTS `dbtodo`.`tbltaskstatuses` (
  `staIdpk` INT NOT NULL AUTO_INCREMENT,
  `staName` VARCHAR(50) NOT NULL,
  `staDescription` VARCHAR(255) NOT NULL,
  `staCreatedDate` DATETIME(6) NOT NULL,
  `staLastEditDate` DATETIME(6) NOT NULL,
  `stIsActive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`staIdpk`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbtodo`.`tbltaskupdates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtodo`.`tbltaskupdates` ;

CREATE TABLE IF NOT EXISTS `dbtodo`.`tbltaskupdates` (
  `tkuIdpk` INT NOT NULL AUTO_INCREMENT,
  `tkuTitle` VARCHAR(255) NOT NULL,
  `tkuDescription` VARCHAR(255) NOT NULL,
  `tkuChallenge` VARCHAR(255) NOT NULL,
  `tkuTkaIdfk` INT NOT NULL,
  `tkuCreatedDate` DATETIME(6) NOT NULL,
  `tkuUpdatedDate` DATETIME(6) NOT NULL,
  `tkuUsrIdfk` INT NOT NULL,
  `tkuProgress` DECIMAL(6,3) NOT NULL,
  PRIMARY KEY (`tkuIdpk`),
  INDEX `tkuTkaIdfk` (`tkuTkaIdfk` ASC) VISIBLE,
  INDEX `tkuUsrIdfk` (`tkuUsrIdfk` ASC) VISIBLE,
  CONSTRAINT `tbltaskupdates_ibfk_1`
    FOREIGN KEY (`tkuTkaIdfk`)
    REFERENCES `dbtodo`.`tbltaskassignments` (`tkaIdpk`),
  CONSTRAINT `tbltaskupdates_ibfk_2`
    FOREIGN KEY (`tkuUsrIdfk`)
    REFERENCES `dbtodo`.`tblusers` (`usrIdpk`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbtodo`.`tblusers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtodo`.`tblusers` ;

CREATE TABLE IF NOT EXISTS `dbtodo`.`tblusers` (
  `usrIdpk` INT NOT NULL AUTO_INCREMENT,
  `usrName` VARCHAR(50) CHARACTER SET 'utf8mb3' NOT NULL,
  `usrFirstName` VARCHAR(25) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `usrLastName` VARCHAR(25) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `usrOtherName` VARCHAR(25) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `usrEmailAddress` VARCHAR(25) CHARACTER SET 'utf8mb3' NOT NULL,
  `usrPassword` VARCHAR(255) NOT NULL,
  `usrCreatedDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `usrLastEditDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `usrLastLoginDate` DATETIME NULL DEFAULT NULL,
  `usrIsActive` BIT(1) NULL DEFAULT b'1',
  PRIMARY KEY (`usrIdpk`),
  UNIQUE INDEX `usrName` (`usrName` ASC) VISIBLE,
  UNIQUE INDEX `usrEmailAddress` (`usrEmailAddress` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
